# This config is equivalent to both the '.circleci/extended/orb-free.yml' and the base '.circleci/config.yml'
version: 2.1

orbs:
  heroku: circleci/heroku@1.2.6

workflows:
  sample:
    jobs:
      - heroku/deploy-via-git:
            tag: build and deploy to Heroku 
            api-key: 'HEROKU_API_KEY'
            app-name: fish-sales-application 
            branch: main         
          # This is the node version to use for the `cimg/node` tag
          # Relevant tags can be found on the CircleCI Developer Hub
          # https://circleci.com/developer/images/image/cimg/node